name: Testing workflow

on: 
  pull_request:
    types: [opened, edited, review_requested, reopened]
    paths:
      - 'lib/**'

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Run on Web 
        working-directory: ./example
        run: |
          flutter pub get
          flutter build web
      - name: Run InteractiveBox test
        run: flutter test
    
  build_window:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Run on Windows
        working-directory: ./example
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
      - name: Run InteractiveBox test
        run: flutter test

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Run on Linux
        working-directory: ./example
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux
      - name: Run InteractiveBox test
        run: flutter test

  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Run on macOS
        working-directory: ./example
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter build macos
      - name: Run InteractiveBox test
        run: flutter test

  build_iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
          architecture: x64
      - name: Run on iOS
        working-directory: ./example
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
      - name: Run InteractiveBox test
        run: flutter test

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Run on Android
        working-directory: ./example
        run: |
          flutter pub get
          flutter build apk 
          flutter build appbundle
      - name: Run InteractiveBox test
        run: flutter test
      
   

    
